#ifndef ERRORHANDLE_H_INCLUDED
#define ERRORHANDLE_H_INCLUDED

// ErrorMessage
#define JVERR_PRIVATE_KEY_NOT_EXIST		1
#define JVERR_PW_MIN_LENGTH_NOT_EXIST	10
#define JVERR_PW_MIN_LENGTH_TOO_SHORT	11
#define JVERR_PW_MAX_LENGTH_NOT_EXIST	12
#define JVERR_PW_MAX_LENGTH_TOO_SHORT	13
#define JVERR_PW_MAX_LENGTH_TOO_LONG	14
#define JVERR_PW_CHARSET_NOT_EXIST		20
#define JVERR_PW_CHARSET_TOO_LONG		21
#define JVERR_PW_CHARSET_DUPLICATE		22
#define JVERR_PW_INITIAL_NOT_EXIST		30
#define JVERR_PW_INITIAL_NOT_VALID		31
#define JVERR_PW_INITIAL_TOO_SHORT		32
#define JVERR_PW_INITIAL_TOO_LONG		33
#define JVERR_PRINT_INTERVAL_NOT_EXIST	40
#define JVERR_PRINT_INTERVAL_TOO_SHORT	41
#define JVERR_PRINT_INTERVAL_TOO_LONG	42
#define JVERR_SEED_ASSERT_FAILED		50

// WarningMessage
#define JVWARN_NOT_ENOUGH_ARGV			101
#define JVWARN_NOT_VALID_ARGV			102
#define JVWARN_RESULT_NOT_OK_FREAD		103
#define JVWARN_RESULT_NOT_OK_FGETS		104

void JV_ErrorHandle(int code);
void JV_WarnHandle(int code);

#endif // ERRORHANDLE_H_INCLUDED
